name: isimo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiofiles=22.1.0=py312h06a4308_0
  - aiosqlite=0.21.0=py312h06a4308_1
  - alsa-lib=1.2.14=h5eee18b_0
  - ambertools=24.8=cuda_None_nompi_py312hbe1986e_101
  - anyio=4.7.0=py312h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_1
  - arpack=3.9.1=nompi_hf03ea27_102
  - asttokens=3.0.0=py312h06a4308_0
  - attr=2.5.1=h166bdaf_1
  - attrs=24.3.0=py312h06a4308_0
  - babel=2.16.0=py312h06a4308_0
  - beautifulsoup4=4.13.4=py312h06a4308_0
  - bleach=6.2.0=py312h06a4308_0
  - blosc=1.21.6=he440d0b_1
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotlicffi=1.0.9.2=py312h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py312h1fdaa30_1
  - chardet=5.2.0=pyhd8ed1ab_3
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py312h06a4308_0
  - contourpy=1.3.3=py312hd9148b4_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dftd4=3.7.0=hd37a5e2_4
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.59.0=py312h8a5da7c_0
  - freetype=2.13.3=ha770c72_1
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.84.3=h89d24bf_0
  - glib-tools=2.84.3=hf516916_0
  - glm=1.0.1=hdd259ec_0
  - graphite2=1.3.14=h295c915_1
  - greenlet=3.2.3=py312h2ec8cdc_0
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - harfbuzz=11.4.2=h15599e2_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h2d575fe_101
  - icu=75.1=he02047a_0
  - idna=3.7=py312h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=6.29.5=py312h06a4308_1
  - ipython=8.20.0=py312h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.8.5=py312h06a4308_0
  - jedi=0.19.2=py312h06a4308_0
  - jinja2=3.1.6=py312h06a4308_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jonquil=0.3.0=h3b12eaf_1
  - json5=0.9.25=py312h06a4308_0
  - jsonschema=4.25.0=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter_client=8.6.3=py312h06a4308_0
  - jupyter_core=5.8.1=py312h06a4308_0
  - jupyter_events=0.12.0=py312h06a4308_0
  - jupyter_server=2.16.0=py312h06a4308_0
  - jupyter_server_fileid=0.9.3=py312h06a4308_0
  - jupyter_server_terminals=0.5.3=py312h06a4308_0
  - jupyter_server_ydoc=0.8.0=py312h06a4308_2
  - jupyter_ydoc=0.2.5=py312h06a4308_0
  - jupyterlab=3.6.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=py312h06a4308_0
  - jupyterlab_server=2.27.3=py312h06a4308_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py312h68727a3_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.3=h6a678d5_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libblas=3.9.0=31_h59b9bed_openblas
  - libboost=1.86.0=hb8260a3_2
  - libboost-python=1.86.0=py312hc39e661_3
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang-cpp20.1=20.1.8=default_hddf928d_0
  - libclang13=20.1.8=default_ha444ac7_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.1.0=h69a702a_4
  - libgfortran-ng=15.1.0=h69a702a_4
  - libgfortran5=15.1.0=hcea5267_4
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.3=hf39c6af_0
  - libglu=9.0.3=h60c0c69_1
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.1.0=h767d61c_3
  - libgpg-error=1.55=h3f2d84a_0
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnetcdf=4.9.2=nompi_h0134ee8_117
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.0=h5eee18b_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.29=ha39b09d_0
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h943b412_0
  - libpq=17.5=h27ae623_0
  - librdkit=2025.03.5=h3c5c181_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libsystemd0=257.7=h4e0b6ca_0
  - libtiff=4.7.0=he137b08_1
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h7b6447c_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=h04c0eec_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.2=py312h5eee18b_0
  - matplotlib-base=3.10.5=py312he3d6523_0
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - mctc-lib=0.4.2=h3b12eaf_0
  - mistune=3.1.2=py312h06a4308_0
  - mkl=2020.2=256
  - mpg123=1.32.9=hc50e24c_0
  - multicharge=0.3.0=hd37a5e2_2
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclassic=1.3.1=py312h06a4308_0
  - nbclient=0.10.2=py312h06a4308_0
  - nbconvert-core=7.16.6=py312h06a4308_0
  - nbformat=5.10.4=py312h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - netcdf-fortran=4.6.2=nompi_h5aa5643_101
  - nglview=2.7.8=pyh59e0f4d_0
  - notebook=6.5.4=pyha770c72_0
  - notebook-shim=0.2.4=py312h06a4308_0
  - nspr=4.37=h29cc59b_0
  - nss=3.115=hc3c8bcf_0
  - numpy=2.3.2=py312h33ff503_0
  - openbabel=3.1.1=py312hbfe4552_9
  - openjpeg=2.5.3=h55fea9a_1
  - openldap=2.6.10=he970967_0
  - openssl=3.5.3=h26f9b46_0
  - overrides=7.4.0=py312h06a4308_0
  - packaging=24.2=py312h06a4308_0
  - pandas=2.3.1=py312hf79963d_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parmed=4.3.0=py312ha9124a0_1
  - parso=0.8.4=py312h06a4308_0
  - pcre2=10.45=hc749103_0
  - perl=5.32.1=7_hd590300_perl5
  - pexpect=4.9.0=py312h06a4308_0
  - pillow=11.3.0=py312h80c1187_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h537e5f6_0
  - platformdirs=4.3.7=py312h06a4308_0
  - ply=3.11=py312h06a4308_1
  - pmw=2.0.1=py312h7900ff3_1008
  - pnab=1.1.6=py312h8572e83_0
  - prometheus_client=0.21.1=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulseaudio-client=17.0=hac146a9_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycairo=1.28.0=py312hac037c1_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=py312h06a4308_0
  - pymol-open-source=3.1.0=py312h40ef045_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyqt=5.15.10=py312h6a678d5_1
  - pyqt5-sip=12.13.0=py312h5eee18b_1
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.0=hab00c5b_0_cpython
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-fastjsonschema=2.20.0=py312h06a4308_0
  - python-json-logger=3.2.1=py312h06a4308_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - pyzmq=26.2.0=py312h6a678d5_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.15=hea1682b_4
  - rdkit=2025.03.5=py312h089baad_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py312h06a4308_0
  - reportlab=4.4.1=py312h66e93f0_0
  - requests=2.32.4=py312h06a4308_0
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - rpds-py=0.22.3=py312h4aa5aa6_0
  - scipy=1.16.1=py312h7a1785b_1
  - send2trash=1.8.2=py312h06a4308_1
  - setuptools=78.1.1=py312h06a4308_0
  - simple-dftd3=1.2.1=h3b12eaf_1
  - sip=6.7.12=py312h6a678d5_1
  - six=1.17.0=py312h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py312h06a4308_0
  - soupsieve=2.5=py312h06a4308_0
  - sqlalchemy=2.0.42=py312h4c3975b_0
  - sqlite=3.31.1=h7b6447c_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tblite=0.4.0=hd37a5e2_2
  - terminado=0.17.1=py312h06a4308_0
  - tinycss2=1.4.0=py312h06a4308_0
  - tk=8.6.13=noxft_hd72426e_102
  - toml-f=0.4.2=h3b12eaf_2
  - tomli=2.0.1=py312h06a4308_1
  - tornado=6.5.1=py312h5eee18b_0
  - traitlets=5.7.1=py312h06a4308_0
  - typing-extensions=4.12.2=py312h06a4308_0
  - typing_extensions=4.12.2=py312h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - urllib3=2.5.0=py312h06a4308_0
  - wcwidth=0.2.13=py312h06a4308_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=1.8.0=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - widgetsnbextension=3.6.10=py312h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xtb=6.7.1=h8876d29_4
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - y-py=0.6.2=py312h4aa5aa6_2
  - yaml=0.2.5=h7b6447c_0
  - ypy-websocket=0.8.4=py312h06a4308_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - alabaster==1.0.0
      - amberutils==21.0
      - annotated-types==0.7.0
      - black==25.1.0
      - click==8.2.1
      - cmake==4.1.0
      - docutils==0.21.2
      - edgembar==3.0
      - f90nml==1.4.5
      - filelock==3.19.1
      - griddataformats==1.0.2
      - imagesize==1.4.1
      - isimo==0.0.1
      - kneed==0.8.5
      - markdown-it-py==3.0.0
      - mda-xdrlib==0.2.0
      - mdanalysis==2.9.0
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mmpbsa-py==16.0
      - mmtf-python==1.1.3
      - mrcfile==1.5.4
      - msgpack==1.1.1
      - mypy-extensions==1.1.0
      - myst-parser==4.0.1
      - nglview-js-widgets==2.7.7
      - packmol-memgen==2025.1.29
      - panedr==0.8.0
      - pathspec==0.12.1
      - pdb4amber==22.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pyedr==0.8.0
      - pymsmt==22.0
      - pytraj==2.0.6
      - rich==14.1.0
      - roman-numerals-py==3.1.0
      - sander==22.0
      - scikit-learn==1.7.2
      - seaborn==0.13.2
      - shellingham==1.5.4
      - snowballstemmer==3.0.1
      - sphinx==8.2.3
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typer==0.16.1
      - typing-inspection==0.4.2
      - xna-builder==0.0.1
prefix: /home/lunet/cgvk2/.conda/envs/isimo
